name: M1 Windows Build
on:
  push:
    branches: [ "codex/gamma-server-authority" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Build DX11 Configuration
      run: msbuild engine-src/src/engine-vs2022.sln /p:Configuration=DX11 /p:Platform=x64 /maxcpucount
    - name: Archive Binaries
      uses: actions/upload-artifact@v3
      with:
        name: xrEngine-Binaries
        path: engine-src/bin/Release/
